"""consolidated_updates_v1

Revision ID: 806905008d5a
Revises: b5093ea1ea6c
Create Date: 2026-02-16 10:30:30.341441

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '806905008d5a'
down_revision = 'b5093ea1ea6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vm_manual', schema=None) as batch_op:
        batch_op.add_column(sa.Column('division_id', sa.BigInteger(), nullable=True))
        batch_op.create_foreign_key(None, 'divisions', ['division_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vm_manual', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('division_id')

    # ### end Alembic commands ###
