"""Add audit logs

Revision ID: 9d85d9135657
Revises: d53f4e00a564
Create Date: 2026-02-11 22:24:18.533364

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9d85d9135657'
down_revision = 'd53f4e00a564'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('system_api')
    with op.batch_alter_table('owners', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.drop_index(batch_op.f('idx_owners_email'))
        batch_op.drop_index(batch_op.f('idx_owners_user'))

    with op.batch_alter_table('user_sessions', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('last_activity',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.drop_index(batch_op.f('idx_user_sessions_token'))
        batch_op.drop_index(batch_op.f('idx_user_sessions_user'))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.drop_index(batch_op.f('idx_users_email'))
        batch_op.drop_index(batch_op.f('idx_users_username'))

    with op.batch_alter_table('vm', schema=None) as batch_op:
        batch_op.alter_column('first_seen_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('last_seen_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.drop_index(batch_op.f('idx_vm_is_deleted'))
        batch_op.drop_index(batch_op.f('idx_vm_name'))
        batch_op.drop_index(batch_op.f('idx_vm_platform_uuid'))
        batch_op.drop_column('inventory_key')

    with op.batch_alter_table('vm_change_history', schema=None) as batch_op:
        batch_op.alter_column('changed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.drop_index(batch_op.f('idx_vm_change_history_changed'))
        batch_op.drop_index(batch_op.f('idx_vm_change_history_type'))
        batch_op.drop_index(batch_op.f('idx_vm_change_history_vm'))

    with op.batch_alter_table('vm_custom_field', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))

    with op.batch_alter_table('vm_disk_fact', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_vm_disk_fact_vm'))

    with op.batch_alter_table('vm_fact', schema=None) as batch_op:
        batch_op.alter_column('raw',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
        batch_op.alter_column('fact_updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.drop_index(batch_op.f('idx_vm_fact_cluster'))
        batch_op.drop_index(batch_op.f('idx_vm_fact_host'))

    with op.batch_alter_table('vm_ip_manual', schema=None) as batch_op:
        batch_op.alter_column('ip_address',
               existing_type=postgresql.INET(),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.drop_index(batch_op.f('idx_vm_ip_manual_ip'))

    with op.batch_alter_table('vm_manual', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.drop_index(batch_op.f('idx_vm_manual_business_owner'))
        batch_op.drop_index(batch_op.f('idx_vm_manual_env'))

    with op.batch_alter_table('vm_nic_fact', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_vm_nic_fact_mac'))
        batch_op.drop_index(batch_op.f('idx_vm_nic_fact_unique'), postgresql_where='(mac_address IS NOT NULL)')
        batch_op.drop_index(batch_op.f('idx_vm_nic_fact_vm'))

    with op.batch_alter_table('vm_nic_ip_fact', schema=None) as batch_op:
        batch_op.alter_column('ip_address',
               existing_type=postgresql.INET(),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.drop_index(batch_op.f('idx_vm_nic_ip_fact_ip'))

    with op.batch_alter_table('vm_sync_run', schema=None) as batch_op:
        batch_op.alter_column('started_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('details',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('idx_vm_sync_run_platform_started'))

    with op.batch_alter_table('vm_tag', schema=None) as batch_op:
        batch_op.alter_column('vm_id',
               existing_type=sa.BIGINT(),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.drop_index(batch_op.f('idx_vm_tag_value'))
        batch_op.drop_index(batch_op.f('idx_vm_tag_vm_id'))
        batch_op.create_index(batch_op.f('ix_vm_tag_vm_id'), ['vm_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vm_tag', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vm_tag_vm_id'))
        batch_op.create_index(batch_op.f('idx_vm_tag_vm_id'), ['vm_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_vm_tag_value'), ['tag_value'], unique=False)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('vm_id',
               existing_type=sa.BIGINT(),
               nullable=False)

    with op.batch_alter_table('vm_sync_run', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_vm_sync_run_platform_started'), ['platform', sa.literal_column('started_at DESC')], unique=False)
        batch_op.alter_column('details',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
        batch_op.alter_column('started_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))

    with op.batch_alter_table('vm_nic_ip_fact', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_vm_nic_ip_fact_ip'), ['ip_address'], unique=False)
        batch_op.alter_column('ip_address',
               existing_type=sa.String(length=50),
               type_=postgresql.INET(),
               existing_nullable=False)

    with op.batch_alter_table('vm_nic_fact', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_vm_nic_fact_vm'), ['vm_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_vm_nic_fact_unique'), ['vm_id', 'mac_address'], unique=True, postgresql_where='(mac_address IS NOT NULL)')
        batch_op.create_index(batch_op.f('idx_vm_nic_fact_mac'), ['mac_address'], unique=False)

    with op.batch_alter_table('vm_manual', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_vm_manual_env'), ['environment'], unique=False)
        batch_op.create_index(batch_op.f('idx_vm_manual_business_owner'), ['business_owner_id'], unique=False)
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))

    with op.batch_alter_table('vm_ip_manual', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_vm_ip_manual_ip'), ['ip_address'], unique=False)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('ip_address',
               existing_type=sa.String(length=50),
               type_=postgresql.INET(),
               existing_nullable=False)

    with op.batch_alter_table('vm_fact', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_vm_fact_host'), ['host_identifier'], unique=False)
        batch_op.create_index(batch_op.f('idx_vm_fact_cluster'), ['cluster_name'], unique=False)
        batch_op.alter_column('fact_updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('raw',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)

    with op.batch_alter_table('vm_disk_fact', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_vm_disk_fact_vm'), ['vm_id'], unique=False)

    with op.batch_alter_table('vm_custom_field', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))

    with op.batch_alter_table('vm_change_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_vm_change_history_vm'), ['vm_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_vm_change_history_type'), ['change_type'], unique=False)
        batch_op.create_index(batch_op.f('idx_vm_change_history_changed'), [sa.literal_column('changed_at DESC')], unique=False)
        batch_op.alter_column('changed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))

    with op.batch_alter_table('vm', schema=None) as batch_op:
        batch_op.add_column(sa.Column('inventory_key', sa.TEXT(), sa.Computed("(((platform)::text || ':'::text) || (vm_uuid)::text)", persisted=True), autoincrement=False, nullable=True))
        batch_op.create_index(batch_op.f('idx_vm_platform_uuid'), ['platform', 'vm_uuid'], unique=False)
        batch_op.create_index(batch_op.f('idx_vm_name'), ['vm_name'], unique=False)
        batch_op.create_index(batch_op.f('idx_vm_is_deleted'), ['is_deleted'], unique=False)
        batch_op.alter_column('last_seen_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('first_seen_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_users_username'), ['username'], unique=False)
        batch_op.create_index(batch_op.f('idx_users_email'), ['email'], unique=False)
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))

    with op.batch_alter_table('user_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_user_sessions_user'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_user_sessions_token'), ['token_hash'], unique=False)
        batch_op.alter_column('last_activity',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))

    with op.batch_alter_table('owners', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_owners_user'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_owners_email'), ['email'], unique=False)
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))

    op.create_table('system_api',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('url', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('method', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('headers', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('payload', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('response_schema', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('resource_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('system_api_pkey'))
    )
    # ### end Alembic commands ###
