"""Initial_migration

Revision ID: b5093ea1ea6c
Revises: 
Create Date: 2026-02-12 10:54:58.128133

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5093ea1ea6c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hosts',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('platform', sa.String(length=20), nullable=False),
    sa.Column('host_id', sa.String(length=100), nullable=False),
    sa.Column('hostname', sa.String(length=255), nullable=False),
    sa.Column('hypervisor_ip', sa.String(length=50), nullable=True),
    sa.Column('hypervisor_name', sa.String(length=255), nullable=True),
    sa.Column('cpu_model', sa.String(length=255), nullable=True),
    sa.Column('cpu_cores_physical', sa.Integer(), nullable=True),
    sa.Column('ram_gb', sa.Integer(), nullable=True),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('platform', 'host_id', name='uq_host_platform_id')
    )
    op.create_table('networks',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('platform', sa.String(length=20), nullable=False),
    sa.Column('network_id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('vlan_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('platform', 'network_id', name='uq_network_platform_id')
    )
    op.create_table('site_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('system_api',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('method', sa.String(length=10), nullable=True),
    sa.Column('headers', sa.JSON(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('response_schema', sa.JSON(), nullable=True),
    sa.Column('resource_type', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('designation', sa.String(length=100), nullable=True),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('must_reset_password', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('vm_sync_run',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('platform', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('vm_count_seen', sa.Integer(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vmware_networks',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('network_id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('network_id')
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=True),
    sa.Column('resource_id', sa.String(length=100), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('owners',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('designation', sa.String(length=100), nullable=True),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('user_sessions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_activity', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_valid', sa.Boolean(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_table('vm',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('platform', sa.String(length=20), nullable=False),
    sa.Column('vm_uuid', sa.String(length=64), nullable=False),
    sa.Column('vm_name', sa.String(length=255), nullable=False),
    sa.Column('bios_uuid', sa.String(length=64), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.Text(), nullable=True),
    sa.Column('delete_reason', sa.Text(), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_sync_run_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['last_sync_run_id'], ['vm_sync_run.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('platform', 'vm_uuid')
    )
    op.create_table('vm_change_history',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('vm_id', sa.BigInteger(), nullable=False),
    sa.Column('sync_run_id', sa.BigInteger(), nullable=True),
    sa.Column('change_type', sa.String(length=50), nullable=False),
    sa.Column('field_name', sa.String(length=100), nullable=False),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('changed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['sync_run_id'], ['vm_sync_run.id'], ),
    sa.ForeignKeyConstraint(['vm_id'], ['vm.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vm_custom_field',
    sa.Column('vm_id', sa.BigInteger(), nullable=False),
    sa.Column('field_key', sa.String(length=100), nullable=False),
    sa.Column('field_value', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_by', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['vm_id'], ['vm.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('vm_id', 'field_key')
    )
    op.create_table('vm_disk_fact',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('vm_id', sa.BigInteger(), nullable=False),
    sa.Column('disk_uuid', sa.String(length=64), nullable=True),
    sa.Column('disk_key', sa.String(length=64), nullable=True),
    sa.Column('disk_label', sa.String(length=255), nullable=True),
    sa.Column('device_type', sa.String(length=50), nullable=True),
    sa.Column('adapter_type', sa.String(length=50), nullable=True),
    sa.Column('size_gb', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('backing_type', sa.String(length=50), nullable=True),
    sa.Column('backing_path', sa.Text(), nullable=True),
    sa.Column('storage_name', sa.String(length=255), nullable=True),
    sa.Column('is_image', sa.Boolean(), nullable=True),
    sa.Column('scsi_bus', sa.Integer(), nullable=True),
    sa.Column('scsi_unit', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['vm_id'], ['vm.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vm_fact',
    sa.Column('vm_id', sa.BigInteger(), nullable=False),
    sa.Column('power_state', sa.String(length=20), nullable=True),
    sa.Column('hypervisor_type', sa.String(length=20), nullable=True),
    sa.Column('cluster_name', sa.String(length=255), nullable=True),
    sa.Column('host_identifier', sa.String(length=255), nullable=True),
    sa.Column('os_type', sa.String(length=255), nullable=True),
    sa.Column('os_family', sa.String(length=50), nullable=True),
    sa.Column('hostname', sa.String(length=255), nullable=True),
    sa.Column('total_vcpus', sa.Integer(), nullable=True),
    sa.Column('num_sockets', sa.Integer(), nullable=True),
    sa.Column('cores_per_socket', sa.Integer(), nullable=True),
    sa.Column('vcpus_per_socket', sa.Integer(), nullable=True),
    sa.Column('threads_per_core', sa.Integer(), nullable=True),
    sa.Column('cpu_hot_add', sa.Boolean(), nullable=True),
    sa.Column('cpu_hot_remove', sa.Boolean(), nullable=True),
    sa.Column('memory_mb', sa.Integer(), nullable=True),
    sa.Column('mem_hot_add', sa.Boolean(), nullable=True),
    sa.Column('mem_hot_add_limit_mb', sa.Integer(), nullable=True),
    sa.Column('total_disks', sa.Integer(), nullable=True),
    sa.Column('total_disk_gb', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('total_nics', sa.Integer(), nullable=True),
    sa.Column('creation_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_update_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('raw', sa.JSON(), nullable=True),
    sa.Column('fact_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['vm_id'], ['vm.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('vm_id')
    )
    op.create_table('vm_ip_manual',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('vm_id', sa.BigInteger(), nullable=False),
    sa.Column('ip_address', sa.String(length=50), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['vm_id'], ['vm.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vm_id', 'ip_address')
    )
    op.create_table('vm_manual',
    sa.Column('vm_id', sa.BigInteger(), nullable=False),
    sa.Column('business_owner_id', sa.BigInteger(), nullable=True),
    sa.Column('technical_owner_id', sa.BigInteger(), nullable=True),
    sa.Column('project_name', sa.String(length=255), nullable=True),
    sa.Column('environment', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('override_power_state', sa.Boolean(), nullable=True),
    sa.Column('override_cluster', sa.Boolean(), nullable=True),
    sa.Column('override_hostname', sa.Boolean(), nullable=True),
    sa.Column('override_os_type', sa.Boolean(), nullable=True),
    sa.Column('override_os_family', sa.Boolean(), nullable=True),
    sa.Column('manual_power_state', sa.String(length=20), nullable=True),
    sa.Column('manual_cluster_name', sa.String(length=255), nullable=True),
    sa.Column('manual_hostname', sa.String(length=255), nullable=True),
    sa.Column('manual_os_type', sa.String(length=100), nullable=True),
    sa.Column('manual_os_family', sa.String(length=50), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_by', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['business_owner_id'], ['owners.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['technical_owner_id'], ['owners.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vm_id'], ['vm.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('vm_id')
    )
    op.create_table('vm_nic_fact',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('vm_id', sa.BigInteger(), nullable=False),
    sa.Column('nic_uuid', sa.String(length=64), nullable=True),
    sa.Column('label', sa.String(length=255), nullable=True),
    sa.Column('mac_address', sa.String(length=32), nullable=True),
    sa.Column('nic_type', sa.String(length=50), nullable=True),
    sa.Column('network_name', sa.String(length=255), nullable=True),
    sa.Column('vlan_mode', sa.String(length=50), nullable=True),
    sa.Column('is_connected', sa.Boolean(), nullable=True),
    sa.Column('state', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['vm_id'], ['vm.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vm_tag',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('vm_id', sa.BigInteger(), nullable=True),
    sa.Column('tag_value', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['vm_id'], ['vm.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vm_tag', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vm_tag_vm_id'), ['vm_id'], unique=False)

    op.create_table('vm_nic_ip_fact',
    sa.Column('nic_id', sa.BigInteger(), nullable=False),
    sa.Column('ip_address', sa.String(length=50), nullable=False),
    sa.Column('ip_type', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['nic_id'], ['vm_nic_fact.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('nic_id', 'ip_address')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vm_nic_ip_fact')
    with op.batch_alter_table('vm_tag', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vm_tag_vm_id'))

    op.drop_table('vm_tag')
    op.drop_table('vm_nic_fact')
    op.drop_table('vm_manual')
    op.drop_table('vm_ip_manual')
    op.drop_table('vm_fact')
    op.drop_table('vm_disk_fact')
    op.drop_table('vm_custom_field')
    op.drop_table('vm_change_history')
    op.drop_table('vm')
    op.drop_table('user_sessions')
    op.drop_table('owners')
    op.drop_table('audit_logs')
    op.drop_table('vmware_networks')
    op.drop_table('vm_sync_run')
    op.drop_table('users')
    op.drop_table('system_api')
    op.drop_table('site_settings')
    op.drop_table('networks')
    op.drop_table('hosts')
    # ### end Alembic commands ###
